# Generated by Django 4.1.5 on 2024-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiestands', '0003_rename_name_cookiestand_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='description',
            field=models.TextField(blank=True, default='no description provided'),
        ),
    ]
